### PR TITLE
Updates commonVersion to 0.59

### PR DESCRIPTION
**Pull request by standpoint**
sets version of jtalks-common up to 0.59 build at maven dependencies.
updates some tests according to changes from jtalks-common 0.58 build.

### CODE REVIEW

**Comment by ctapobep** [comment]
The commit message should start with the task ID: POULPE-528. Also there is no place for HTML in the commit message - the format is close to Markdown.

**Comment by standpoint** [comment]
@ctapobep, the commit message has been already corrected.

**Comment by ctapobep** [comment]
I've merge the commit. But please update your local branches since you're sitting on old commits.

**Comment by standpoint** [comment]
Thanks! I've already updated local branches

**Pull request closed without merging**
